### ISSUE TITLE
Node tree error when I open a file

### ISSUE THREAD

**Issue by aldomontanari** [ladybug-tools/ladybug-blender#10]
Steps: 
Follow Moult's demo video (https://www.youtube.com/watch?v=rMCuSwsF2aM&feature=emb_logo). 
Save & close.
Open saved file -> It doesnt work

Screenshot
![imagen](https://user-images.githubusercontent.com/32773354/94931361-0e86ef00-049e-11eb-8378-23d60af6f774.png)

Click 'refresh' -> Error report:

Traceback (most recent call last):
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\ladybug_tools\nodes\ladybug\LB_Out.py", line 31, in execute
    node.refresh()
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\ladybug_tools\nodes\ladybug\LB_Out.py", line 57, in refresh
    self.process()
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\ladybug_tools\nodes\ladybug\LB_Out.py", line 74, in process
    for geometries in socket.sv_get():
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sverchok-master\core\sockets.py", line 125, in sv_get
    return self.convert_data(SvGetSocket(self, deepcopy), implicit_conversions)
  File "C:\Users\aldom\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sverchok-master\core\socket_data.py", line 121, in SvGetSocket
    raise SvNoDataError(socket, msg="not found in socket_data_cache")
sverchok.core.socket_data.SvNoDataError: node LB Out.001 (socket geometry) not found in socket_data_cache

File:
[LadybugTest.zip](https://github.com/ladybug-tools/ladybug-blender/files/5318418/LadybugTest.zip)

Blender version: 2.90.0 Alpha
OS: Windows 10

**Comment by ppaawweeuu** [comment]
I can not reproduce that error. Win7, b3d 2.9, sv 0.6.
Can it be too much data? I see that you left blank `LB Analisys Period` , It means every hour from 1st Jan to 31th Dec,(24hx365d=8760 rays for subdivided square). And two analisys, direct lights and temperature. My computer slows down.
To feed some numbers into `LB Analisys Period` you can not type it, you need to use `A Number` nodes. 
see issue #4

**Comment by Durman** [comment]
If such problems (`SvNoDataError`) happen this two buttons can help.

![2020-10-04_06-57-45](https://user-images.githubusercontent.com/28003269/95005915-f4205300-060e-11eb-822d-b883f0a89694.png)

**Comment by ppaawweeuu** [comment]
Ok, I see that error a lot. Hard to find any pattern. It is like node sockets keep data from previous iterations, is it possible?

Sometimes I can generate shadows from object/mesh I deleted and purged:

![ghost](https://user-images.githubusercontent.com/61344631/95026638-0ba11f80-0693-11eb-91ef-5d14b78325b4.JPG)

After reseting node and updating tree i see error like @aldomontanari 

![ghost_after](https://user-images.githubusercontent.com/61344631/95026711-8ff3a280-0693-11eb-9676-4351eb2c902c.jpg)

**Comment by andremeireles** [comment]
@aldomontanari I see that is missing a Cube.
If you make one and reassign the selection on **Object In** node, the error goes away.
Tested and confirmed.

Blender 2.90.1 - Sverchok 0.6.0.0 - Ladybug 0.0.20927 - Manjaro

**Comment by aldomontanari** [comment]
You are right, problem solved.
