### ISSUE TITLE
LB Out Refresh = Create new copy of everything

### ISSUE THREAD

**Issue by ppaawweeuu** [ladybug-tools/ladybug-blender#11]
Refreshing `LB Out` node creates new set of geometry.
I belive that only reason is early stage development. Am I right?
Now I just delete everything, purge file, refresh.

**Comment by Moult** [comment]
Correct.

I plan to:

 - At the very least, make it keep track of what its generated, and purge the old objects when you press refresh
 - Allow more things to be drawn unbaked via OpenGL, then turn baking into an explicit operation

**Comment by ppaawweeuu** [comment]
Great.
I see `LB Out` works/recompute something everytime I connect/disconnect sockets. More data more lags, file from #10 is great example.
Can it be muted and calculated only with some'Refresh' button.

**Comment by Moult** [comment]
Actually, the node _prior_ to `LB Out` recomputes every time you connect / disconnect sockets. Basically, when a node will never calculate until you hook in an output node. Some of these nodes take time, e.g. solar hours analysis. It's not actually the `LB Out` node which is lagging, it's the node prior to it (likely your analysis node).

Some analysis nodes actually uncleanly create some geometry that isn't garbage collected at the moment (e.g. some meshes have their modifiers resolved). This gives the impression that the `LB Out` node is doing work, when in fact it is the prior node. This is also on the to-do list to fix.

**Comment by ppaawweeuu** [comment]
Thanks for clarifications. Waiting for next release.
