### ISSUE TITLE
SunPath and LB Parameters 

### ISSUE THREAD

**Issue by seamoo** [ladybug-tools/ladybug-blender#17]
I've created a sun path and added dry bulb temp data overlay. When I’m hooking in the LB Legend Parameters node I’m seeing its changing the orientation of the legend of the sun path, the text is getting rotated and overlapped with the legend. I'm using Blender v 2.9.0. 

![LegendAfterLPPadded](https://user-images.githubusercontent.com/25322402/95183779-14553b00-07e4-11eb-896f-e469f7ba10fc.jpg)
ppen under LB for GH.

![LegendBeforeLPPadded](https://user-images.githubusercontent.com/25322402/95183797-1a4b1c00-07e4-11eb-8bbc-c2736be10141.jpg)

**Comment by mostaphaRoudsari** [comment]
Hi @seamoo, thank you for reporting this issue.

I don't really know why this is happening. Can it be that the default input for vertical or horizontal is set to false by default in the node and that's why the legend is changing to horizontal?

**Comment by seamoo** [comment]
> Hi @seamoo, thank you for reporting this issue.
> 
> I don't really know why this is happening. Can it be that the default input for vertical or horizontal is set to false by default in the node and that's why the legend is changing to horizontal?

Hi @mostaphaRoudsari . OK. When I hook in the legend parameter it changes the legend
![lblptrue](https://user-images.githubusercontent.com/25322402/95209928-89d30280-0808-11eb-9872-16050be72523.JPG)
 from vertical to horizontal. When I add a boolean 'False' its changed back to the verical legend and 'True' makes it horizontal.

**Comment by mostaphaRoudsari** [comment]
> from vertical to horizontal. When I add a boolean 'False' its changed back to the verical legend and 'True' makes it horizontal.

This is reversed from what it should be working. Not sure why this is happening. Probably an issue with how we set the default value for this Boolean.

**Comment by Moult** [comment]
@seamoo I just tested and I see True = vertical, False = horizontal, which is what I expect. It defaults to False. Perhaps [the defaults](https://github.com/ladybug-tools/ladybug-grasshopper/blob/master/ladybug_grasshopper/json/LB_Legend_Parameters.json#L65-L71) should be changed upstream?

As for the overlapping text, when I first implemented text, I thought for some reason the font units were too small, so I arbitrarily multiplied font sizes by 2. That was a mistake, and so now I've reverted it back to how Ladybug intended it. You will notice all text shrinking now, but they won't overlap. So I guess that's fixed.

**Comment by mostaphaRoudsari** [comment]
It looks like we need to do another pass of the components in Grasshopper and make sure all the default values that are needed are set for each input.

cc: @chriswmackey

**Comment by seamoo** [comment]
@Moult description now working great when you hover over the input / output. For the Legend Parameter the text or the node does need updating. The text indictaes the detault is TRUE and will give a Vertical Legend. The default is actually False as it creates a vertical legend when this node is plugged in.

![LegendPosition](https://user-images.githubusercontent.com/25322402/95426595-c5ceaa80-0963-11eb-85d0-26c0f3962a00.JPG)

**Comment by Moult** [comment]
@seamoo thanks for the report about the missing defaults! This is reported in #16 and so I'll need to wait until its fixed upstream before this fix propagates to Blender. Closing as the text issue is fixed, and the legend defaults is captured in #16.
