### ISSUE TITLE
Helper Text 

### ISSUE THREAD

**Issue by seamoo** [ladybug-tools/ladybug-blender#19]
A feature I really liked in learning LB in GH was the text helpers when you hover over input/output text in a component. Especially now LB has gone to 1.0.0 I find new inputs and outputs or things have been moved our relabelled. I'm finding I need to have GH open to understand what these mean and what I may need to connect. . 

Some users may / will be coming to LB for the first time and may not have access to Rhino license to run GH/LB. In this case they will be at a disadvantage. Implementing a similar feature in Blender or by creating stand along wiki to describe the node and its input and output functions would be invaluable for new users.

I do see this was rasied in the past ([https://github.com/nortikin/sverchok/issues/3569](https://github.com/nortikin/sverchok/issues/3569))

As an idea I did find the very helpful _Examples_ included in Sverchok. Could LB specific examples be added for LB here to allow users understand typical builds for common problems. This would be helpful for new users or those coming from GH to understand Sverchok 'A Number', 'True' and 'Note' and how they relate to inputs in Blender GH.

![Examples](https://user-images.githubusercontent.com/25322402/95228060-80ec2c00-081c-11eb-9e85-bcbb952e8ed9.JPG)

**Comment by Moult** [comment]
Descriptions have now been added for inputs, outputs, and the nodes themselves. Note that the terminology used is still things like Grasshopper, Rhino, and Component. Ping @mostaphaRoudsari / @chriswmackey - I can replace these, but do you want to use template tags like for the code?

**Comment by mostaphaRoudsari** [comment]
Hi @Moult, Nice one! Descriptions are key to be able to use Ladybug Tools plugins.

I'll be a fan of creating a template since it will be helpful for other platforms too. Are we talking about the same ones that we use for the code itself? We should probably open a new issue for this one and assign it to me.

**Comment by Moult** [comment]
Cheers - in that case, this bug is now resolved.
