### ISSUE TITLE
Issue with File Path + LB Import EPW

### ISSUE THREAD

**Issue by JitQL** [ladybug-tools/ladybug-blender#24]
@mostaphaRoudsari 

I imported [this](https://energyplus.net/weather-download/europe_wmo_region_6/PRT//PRT_Lisboa.085360_INETI/PRT_Lisboa.085360_INETI.epw) epw file from here:

https://energyplus.net/weather-location/europe_wmo_region_6/PRT//PRT_Lisboa.085360_INETI

I wanted to follow this node setup @Moult made:

https://community.osarch.org/uploads/editor/qs/c2uhyuuo493e.png

However, the "LB Import EPW" Node turns red as soon as I plug it to the "LB Wind Rose" and as you can see here, it seems it doesn't find the file in C:

![image](https://user-images.githubusercontent.com/71294919/95732129-4ea55900-0c78-11eb-9bba-1de969a87978.png)

**Comment by Moult** [comment]
Hmm, can't seem to replicate - are you sure you downloaded the file correctly? Can you connect a stethoscope to the output of the `File Path` node, and double check that that file contains valid EPW data? Also, are there any accents or funny characters in the path?

![image](https://user-images.githubusercontent.com/88302/95736959-b12b4300-0cd2-11eb-80c5-288ac60837a0.png)

**Comment by JitQL** [comment]
No good for me.

![image](https://user-images.githubusercontent.com/71294919/95739369-a5b02b80-0c82-11eb-92c3-543d96806173.png)

**Comment by JitQL** [comment]
Now, I went to the sverchok addon and updated it as well as every extra function that I had installed and Sverchok doesn't even start.

I'm getting this error in the console:
```

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Joao\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sverchok-master\__init__.py", line 74, in <module>
    node_list = make_node_list(nodes)
NameError: name 'nodes' is not defined

```

**Comment by Durman** [comment]
Restart Blender?

**Comment by JitQL** [comment]
So I reinstalled Sverchok and reinstalled LB tools and I now have this:

![image](https://user-images.githubusercontent.com/71294919/95740965-57e8f280-0c85-11eb-8842-3a90fe25de25.png)


It seems to be working? Will test further

**Comment by JitQL** [comment]
Now I have an error further down the road on the "LB Wind Rose" node. I'm trying to reproduce what you did on the wind output before and showed in OSArch:

![image](https://user-images.githubusercontent.com/71294919/95741917-0e99a280-0c87-11eb-82b5-b760914d1567.png)

**Comment by JitQL** [comment]
> Restart Blender?

Yes I restarted it several times and then went on uninstalling Sverchok and Ladybug. After reinstall that problem got fixed but now I had the new one above. It is still there after restaring Blender.

**Comment by Moult** [comment]
See #21

**Comment by JitQL** [comment]
Ok I saw it and will try. Thanks!

**Comment by JitQL** [comment]
Looking better! Looking technical!

But... I've got a red alert on the LB Out node now. I'm thinking I should be back dealing with simpler stuff. Can you help out again?

![image](https://user-images.githubusercontent.com/71294919/95766454-326edf80-0cab-11eb-960e-45ab0013c4d9.png)

**Comment by Moult** [comment]
You need to install the point cloud visualiser add-on. It's in the instructions in the [readme](https://github.com/ladybug-tools/ladybug-blender/)

**Comment by JitQL** [comment]
Oops. Sorry. I had read it 2 weeks ago, but only had time to install Sunday. Thanks for your patience and help.

**Comment by Moult** [comment]
No worries, is it fixed? If so, we can close this bug :)

**Comment by JitQL** [comment]
Sorry, I couldn't find a way to install the point cloud visualizer add-on. That link in the ladybug read gives access to some code but neither the read me nor the code landing page explain how to use it with blender. I don't want to abuse on my luck but can you give me a few more pointers?

For what's worth though, the original bug is indeed fixed. It probably should even be considered as non existent. Thank you!

**Comment by JitQL** [comment]
I've been searching online and I think I understood it now. Blender add-ons are either py or zip files. I thought they were always zip. I guess that file you pointed me to is a py. I'll try it again tomorrow.

Sorry for being such a noob but between learning blender, freedcad, sverchok and getting to grips with git hub, so I can finally use BlenderBIM and now ladybug tools, I'm having more questions than it would be wise.

**Comment by JitQL** [comment]
So I installed the pointcloud python script and LB finds the script, but some error is being produced. I will opena new bug so you can close this one.
