### ISSUE TITLE
Pointcloud script is returning an error in LB Out

### ISSUE THREAD

**Issue by JitQL** [ladybug-tools/ladybug-blender#25]
As you can see on the image below:

![image](https://user-images.githubusercontent.com/71294919/95974628-24d16b00-0e0d-11eb-98ec-b8d6a6151026.png)

**Comment by Moult** [comment]
I don't think you downloaded the correct point cloud visualiser file. It looks like you've downloaded a webpage, not the file. This is the file you're after: https://raw.githubusercontent.com/uhlik/bpy/master/space_view3d_point_cloud_visualizer.py

But all in all, I think this could be improved. Either bundled with the add-on, or drawn using opengl as suggested in #5. This would make it easier for users.

**Comment by JitQL** [comment]
You were right! 

Here is the result:

![image](https://user-images.githubusercontent.com/71294919/96100365-34fc4f80-0ecc-11eb-9119-78749c14ec2c.png)

I guess close another non existng issue... All of them are making me look very bad! :)

I'm going to share this with an engineer I'm working with and we are going to spend our spare time working on a workflow around these tools. Both of us are unexperienced on both Blender and Energy analysis tools, but we are going to be learning in the next months and hopefully help by sharing our experiences as we grow along.

Thanks again for all your hardwork and help!
