### ISSUE TITLE
LB Out node won't refresh

### ISSUE THREAD

**Issue by KatKapusta** [ladybug-tools/ladybug-blender#28]
Hi,
running: Blender 2.93, ladybug 201010

a newbie here:) I've only installed Sverchok, LB and BlenderBIM on a fresh Blender 2.93 today, along with Python 3.95, and tried to follow the tutorial to make a solar diagram (https://www.youtube.com/watch?v=rMCuSwsF2aM). 
However, I run into the same bug whenever I try to refresh the LB Out (line 32, ..., location: <unknown location>). This way, I can only get one piece of geometry displayed.
![image](https://user-images.githubusercontent.com/21269709/122433974-fd7ffe80-cf96-11eb-9e10-59ea2120fe14.png)
Is there a way to go around it?
Thanks and kudos for so much awesome work!

**Comment by oktkhr0916** [comment]
I have same problem. I hope too.
My Environment : blender(2.93), sverhok(v1.0.0-beta stable june30_2020) , ladybug-blender(201010)

And I also want to know which versions combination is working well at blender, sverhok and ladybug-blender?
Thank you.

**Comment by Durman** [comment]
This changes I guess were a cause
https://github.com/nortikin/sverchok/pull/4070

**Comment by oktkhr0916** [comment]
Thank you. I confirmed that worked well with [this version](https://github.com/nortikin/sverchok/tree/vstable8).

**Comment by onceadrog** [comment]
Applying this fix also resolves issue #32

**Comment by Moult** [comment]
@onceadrog can you submit a PR?

**Comment by onceadrog** [comment]
Pull Request? Why? I just overwrote my LB_Out.py with the new version on master from this fix

**Comment by Moult** [comment]
@onceadrog oh sorry, I didn't fully read the thread and only quickly skimmed through :) nevermind!
