### ISSUE TITLE
Missing Nodes - Location & Sun Position

### ISSUE THREAD

**Issue by ppaawweeuu** [ladybug-tools/ladybug-blender#3]
Location & Sun Position nodes seems to be missing. Blender 2.83 & 2.9.
Console after lunching Blender:

![b3d_2 83_start_logs](https://user-images.githubusercontent.com/61344631/94488064-419d5a00-01e2-11eb-8a68-d3d37f42432b.PNG)

After installing Ladybug dependency using PIP...

![ladybud_install_with_pip](https://user-images.githubusercontent.com/61344631/94488273-9b058900-01e2-11eb-96a1-abbb8b088013.PNG)

Both seems to be in place, but there are 2 Ladybugs in menu.

![ladybug_twice](https://user-images.githubusercontent.com/61344631/94488692-5e865d00-01e3-11eb-955a-62493f2b5a8d.gif)

**Comment by Moult** [comment]
Ah sorry for the confusion, that's the old Ladybug that was bundled with Sverchok and needs to be removed.

I've now purged the old ladybug, there should be no need to pip install anything, and there should now only be one ladybug.

https://github.com/nortikin/sverchok/commit/eb7d5c42b11d7aacb2d5adbbbb2598d995ea1e40

Can you try remove sverchok and reinstall?

**Comment by Moult** [comment]
Accidentally closed this with a commit, but it's fixed anyway so should be all good.

That commit was mean to fix #4.

**Comment by ppaawweeuu** [comment]
> Can you try remove sverchok and reinstall?

done. reinstalled, works. thx
