### ISSUE TITLE
LB Import EPW cannot handle EPW CSV files?

### ISSUE THREAD

**Issue by onceadrog** [ladybug-tools/ladybug-blender#31]
The LB Import EPW node throws various errors when handling an EPW CSV file.

Mainly indexError('list index out of range') but also string to float parsing errors, depending on fields, etc.

What file specification is being used?

**Comment by mostaphaRoudsari** [comment]
Hi @onceadrog, Can you share the epw file? It should handle any standard epw file.

**Comment by onceadrog** [comment]
I dug into the file specification document, the downloaded EPW had some misaligned location fields (which I had fixed to get past the initial errors) and was but it also doesn't have valid [datasource] information in field 6 of all the daily data (i.e. "9" instead of something like "C9C9C9C9*0?9?9?9?9?9?9?9*0C8C8C8C8*0*0E8*0*0").
Weird thing is that the file works in other software without complaint....

Looks like I might need to reverse engineer the datasource field to provide a valid file.

**Comment by onceadrog** [comment]
Actually, I've found some other issues in the EPW parsing as part of my testing:
1. It doesn't respect the actual "header analysis period", always looks for 8760 records regardless of actual analysis period of file
- e.g. Truncate data records to a single day, and set data period header to reflect (1/1 instead of 31/12)
2. It doesn't respect leap year data which has an extra 24 records (and therefore has 8784 which is != 8760 either

**Comment by onceadrog** [comment]
I found it. There were a couple of empty fields. I thought it was just a poorly parsed error message, given it gave no traceback info at all. It was actually reporting the content of the individual field within the string it was trying to convert:
  ladybug.epw:663 - ERROR - could not convert string to float: '' 

Code fix: if NULL use zero....
File fix within data rows: replace ",," with ",0,"

**Comment by onceadrog** [comment]
Not that I can output anything anyway due to issue #32.
Time to spend a few hours chasing that one down I guess...

**Comment by onceadrog** [comment]
Fixing nulls in the EPW CSV fields solved this, along with the Sverchok fix which cleared the other blocker #32
