### ISSUE TITLE
LB Out throws errors every time

### ISSUE THREAD

**Issue by onceadrog** [ladybug-tools/ladybug-blender#32]
Blender 2.93.0 following basic use example at https://www.youtube.com/watch?v=rMCuSwsF2aM
Blender OSM add-on disabled (as per console notes for Sverchok) 
![image](https://user-images.githubusercontent.com/6299372/127400445-36fc4f1c-8c5a-4edb-b6f5-697b1c3bb906.png)

**Comment by onceadrog** [comment]
I chased down this bug in LB_Out.py, and then discovered there is a fresh fix to the file ( issue #28 ) which solves it (variable name didn't align with Sverchok). 
This seems like a critical bug in the release version, consider pushing out an updated release to resolve?

**Comment by ebo** [comment]
Can you post a file that works and another that recreates this error?  I believe that I have too stumbled across it using USA_MD_Baltimore.724060_TMY2.epw

**Comment by ebo** [comment]
when will they have a new release?

**Comment by Moult** [comment]
Thanks @ebo - this has been so far down my TODO list but I managed to squeeze in some time to create a new build. https://blenderbim.org/download.html

Closing as fixed.

**Comment by ebo** [comment]
Woo Hoo!  thank you.
