### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by michaldengusiak** [ladybug-tools/ladybug-blender#35]
Hi,

I managed to install Blender and sverchok but I am struggling with the ladybug. Unable to find it?
Can you please guide me...

![image](https://user-images.githubusercontent.com/26113670/136194327-59cc0c83-2edd-43a0-b270-be7a2474fecd.png)

![image](https://user-images.githubusercontent.com/26113670/136194493-f2d28c0e-77c7-41ee-9dac-c249289159b2.png)

![image](https://user-images.githubusercontent.com/26113670/136194597-9d5a0670-4627-4699-80e9-8ff67bb3badd.png)

**Comment by mostaphaRoudsari** [comment]
Hi @michaldengusiak, did you follow the instructions here?

https://github.com/ladybug-tools/ladybug-blender#installation

**Comment by Moult** [comment]
New builds are out with all sorts of fixes: https://blenderbim.org/download.html

Closing.
