### ISSUE TITLE
LB Out Error

### ISSUE THREAD

**Issue by TZwielehner** [ladybug-tools/ladybug-blender#38]
I get the following error:
```
Python: Traceback (most recent call last):
  File "C:\Users\abc\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\ladybug_tools\nodes\ladybug\LB_Out.py", line 33, in execute
    node.refresh()
TypeError: 'bool' object is not callable
```
The LB SunPath node analemma shows a nested list ([[[Polyline3D...).

**Comment by helenkwok** [comment]
I also get the same error. I connect analemma to the note node and get this:
```
[[[Polyline3D (5 vertices), Polyline3D (8 vertices), Polyline3D (12 vertices), Polyline3D (13 vertices), Polyline3D (13 vertices), Polyline3D (13 vertices), Polyline3D (13 vertices), Polyline3D (13 vertices), Polyline3D (13 vertices), Polyline3D (13 vertices), Polyline3D (13 vertices), Polyline3D (13 vertices), Polyline3D (12 vertices), Polyline3D (8 vertices), Polyline3D (5 vertices)]]]
```
I am using Blender 3.4, Sverchok 1.1 and Ladybug Tools 0.0.220127

**Comment by Feihei** [comment]
I also met with this error, using blender 3.4.1 , sverchok 1.1 and Ladybug Tools 0.0.220127
I guess it was because sverchok changed the behavior of the node.refresh() method now it returns a boolean
I also tried blender 2.93 and several early versions of sverchok, but no help :(
