### ISSUE TITLE
LB Out Refresh + Undo -> Close Blender

### ISSUE THREAD

**Issue by ppaawweeuu** [ladybug-tools/ladybug-blender#6]
I noticed strange behavior:
1. I connect sockets
2. press Refresh button
3. immadietly press ctrl+z (same with undo from menu)
that crush Blender, but (?!)...
...if after Refresh i do anything (move any node, or even select/deselect anything, or even click LMB anywhere) there is no problem.
Can someone reproduce that problem?

![LB_Out_bug](https://user-images.githubusercontent.com/61344631/94624646-35370100-02b7-11eb-963f-6268151e6747.JPG)

**Comment by Durman** [comment]
https://docs.blender.org/api/current/info_gotcha.html#help-my-script-crashes-blender
