### ISSUE TITLE
Edit Source button does not work

### ISSUE THREAD

**Issue by ppaawweeuu** [ladybug-tools/ladybug-blender#8]
Edit Source button does not work. Error msg:

![edit_source_button](https://user-images.githubusercontent.com/61344631/94625876-1f770b00-02ba-11eb-85ea-b6bf7b4ba130.JPG)

**Comment by Moult** [comment]
I don't think this is an error with Ladybug. I tried it with a regular Sverchok node and got the same error. I'm not entirely sure how that is meant to work. I've created a bugreport on Sverchok and we'll see what comes out of it :)

**Comment by ppaawweeuu** [comment]
@Moult , see here: https://github.com/nortikin/sverchok/issues/3602#issuecomment-702416406

**Comment by Moult** [comment]
Fixed upstream.
